### ISSUE TITLE
打开了OnlineMode验证的服务器进不去

### ISSUE THREAD

**Issue by yqs112358** [ddf8196/FakePlayer#1]
有没有兴趣加上给微软的正版验证？
这个假人项目好多服务器都很有需求

**Comment by yqs112358** [comment]
发现问题不在OnlineMode
而是FakePlayer与白名单冲突
将白名单关闭之后就可以正常使用了

**Comment by yqs112358** [comment]
我是憨批
白名单里把xuid删了就能进了

**Comment by ddf8196** [comment]
假人在正确配置公钥后可以通过正版验证
如果服务器开启了白名单，需要手动将假人添加到白名单

**Comment by yqs112358** [comment]
> 假人在正确配置公钥后可以通过正版验证
> 如果服务器开启了白名单，需要手动将假人添加到白名单

蟹蟹指导~这个假人挺好用的
