### ISSUE TITLE
假人似乎无法加载烈焰人刷怪笼

### ISSUE THREAD

**Issue by win-researcher** [ddf8196/FakePlayer#23]
服务器：版本BDS 1.17.11.01，加载距离4区块，没有addon或行为包，难度普通，生物生成，生物破坏等已开启
假人被设置在烈焰人刷怪笼上方3格处，但若正常玩家不在刷怪笼附近，刷怪笼不刷新烈焰人。更换假人位置没有效果。

**Comment by ddf8196** [comment]
试试让假人在地狱断开连接后重新连接

**Comment by win-researcher** [comment]
> 试试让假人在地狱断开连接后重新连接

实测无效

**Comment by win-researcher** [comment]
已解决
