### ISSUE TITLE
feature: add a english gui option 

### ISSUE THREAD

**Issue by Tommie1236** [ddf8196/FakePlayer#27]
an request to add a enlish version of the gui for people that cant read chinese gui

**Comment by Jasonzyt** [comment]
https://github.com/ddf8196/FakePlayer/commit/0b13f5626663d7a74324e83e8a2b4ec4303543af

**Comment by Tommie1236** [comment]
I see that Initial support for multiple languages is added. Can i already change the language? And if so, how?

**Comment by ddf8196** [comment]
To change the language to English, you can download the latest version from [Releases](https://github.com/ddf8196/FakePlayer/releases/latest) or [Actions](https://github.com/ddf8196/FakePlayer/actions) and change the `language` in `config.yml` to `en-us`

**Comment by Tommie1236** [comment]
That worked. Thanks for adding this, it makes my life a whole lot easier.
