### ISSUE TITLE
希望能加入自动复活功能

### ISSUE THREAD

**Issue by pa733** [ddf8196/FakePlayer#3]
如果游戏内假人被玩家打死，那么需要重启假人程序才能复活，建议自动检测假人状态并复活假人

**Comment by ddf8196** [comment]
复活方式正在分析，完成以后会增加自动复活功能的

**Comment by yqs112358** [comment]
> 如果游戏内假人被玩家打死，那么需要重启假人程序才能复活，建议自动检测假人状态并复活假人

目前可以用先remove再add来重生不用重启emmm

**Comment by ddf8196** [comment]
自动复活已实现
