### ISSUE TITLE
能否更新1.17.32.02版本

### ISSUE THREAD

**Issue by EthicalNine4070** [ddf8196/FakePlayer#31]
找到您做的机器人插件,想在服务器使用，请问什么时候更新新版本？

**Comment by xiaoqch** [comment]
> 找到您做的机器人插件,想在服务器使用，请问什么时候更新新版本？

你可以在github action最新构建下载到支持1.17.3x的版本
https://github.com/ddf8196/FakePlayer/actions/runs/1266223044
