### ISSUE TITLE
关于如何在BDS开了在线验证（online-mode=true）的情况下添加假人的提问

### ISSUE THREAD

**Issue by VtaSkywalker** [ddf8196/FakePlayer#4]
开服版本：BDS 1.16.4
当前状况：
    BDS处：已开启在线验证（白名单需要开启在线验证才能用），并开启了白名单，添加了假人的名字（tool_man_1）并已执行过whitelist reload
    FakePlayer处：已配置好公钥并添加至server.properties中，在没有开启在线验证时能够成功添加假人。但在开启了在线验证后，添加的假人会不断地显示连接中、断开连接和重连（从BDS处可以发现它们没有加入游戏）

因此想在这里请教一下，如何在BDS开了在线验证的情况下，向服务器内添加假人

**Comment by ddf8196** [comment]
建议检查server.properties中trusted-key的值和配置文件中serverPublicKey的值是否完全相同

**Comment by ddf8196** [comment]
假人已经处理了在线验证，公钥正确配置的情况下完全可以通过验证

**Comment by VtaSkywalker** [comment]
> 建议检查server.properties中trusted-key的值和配置文件中serverPublicKey的值是否完全相同

好的，谢谢！

**Comment by VtaSkywalker** [comment]
> 假人已经处理了在线验证，公钥正确配置的情况下完全可以通过验证

嗯，我们这边现在也成功加进来了。是我的操作失误，重复打了两次"trusted-key="……感谢提醒！
