### ISSUE TITLE
linux/ubuntu 启动fakeplayer

### ISSUE THREAD

**Issue by jason64123** [ddf8196/FakePlayer#40]
我想搭一个自动伺服器给fakeplayer，但是ubuntu和linux不能启动.bat能启动但是开不了，我安装了wine拿来启动exe/bat的但是打了指令看到指令版出来一下就没了 除非我自己吧bat里面的内容改去sh 如果已经有做好的可以通知我 感谢 @羊肉

**Comment by ddf8196** [comment]
bin目录中的无扩展名文件就是linux下的启动脚本

**Comment by jason64123** [comment]
感谢 感谢 因为没放.sh所以没去看
