### ISSUE TITLE
面板伺服器server.properties不给加公钥

### ISSUE THREAD

**Issue by jason64123** [ddf8196/FakePlayer#43]
能改的只有  他不给自己上传自己的server.properties 因为要开白名单 所以一定要开online mod
![148632006-799e2217-926d-4c21-94ee-a20ded31405b](https://user-images.githubusercontent.com/81096523/148632101-72a2b885-102a-4eb0-a824-f5afa5556498.png)

**Comment by Jasonzyt** [comment]
你这个真没办法，能装插件的话应该可以靠插件修改key
