### ISSUE TITLE
不懂

### ISSUE THREAD

**Issue by jason64123** [ddf8196/FakePlayer#47]
协议版本获取失败,尝试使用默认协议版本(408)连接   我用的就是默认的 还是伺服器问题？
![image](https://user-images.githubusercontent.com/81096523/151010147-925671da-8fa7-42e1-a1a1-d622bee1911a.png)

**Comment by ddf8196** [comment]
检查服务器地址和端口是否正确

**Comment by jason64123** [comment]
那个伺服器是replit的

**Comment by jason64123** [comment]
我猜应该是replit的java问题 因为自己的ubuntu20.04可以连接到 看看作者怎么说
![image](https://user-images.githubusercontent.com/81096523/151024515-709b1221-a47c-4a21-847c-77b03e6926a4.png)
