### ISSUE TITLE
假人的背包无法正确使用

### ISSUE THREAD

**Issue by sxk2004** [ddf8196/FakePlayer#48]
无论假人背包里有多少东西，用指令查询时都会回复“无”，有时候甚至东西拿在手上都回复“无”

**Comment by sxk2004** [comment]
用指令让他丢东西也不听，只有杀死了才会掉东西出来

**Comment by ddf8196** [comment]
游戏版本和假人版本是多少

**Comment by sxk2004** [comment]
游戏版本1.18.1，假人版本0.5-2

**Comment by sxk2004** [comment]
假人版本是0.5.2，刚刚发错了

**Comment by ddf8196** [comment]
试试[Actions](https://github.com/ddf8196/FakePlayer/actions)中的最新版本

**Comment by sxk2004** [comment]
解决了，谢谢
