### ISSUE TITLE
假人在地狱加载的三叉戟击杀生物没有掉落物？

### ISSUE THREAD

**Issue by win-researcher** [ddf8196/FakePlayer#52]
服务端版本：1.18.12 with LiteloaderBDS 2.1.3
假人版本：0.5.3-alpha
加载距离6区块 难度普通 生物生成开启 

一个烈焰人刷怪塔（用三叉戟绞肉机实现自动击杀），假人在烈焰人刷怪笼下方8格处挂机，但这个刷怪塔当正常玩家不在旁边时就没有产物，主世界里其他三个同样由假人加载并用了三叉戟绞肉机的刷怪塔都能正常工作。
加载BehaviorLog行为监控日志插件并运行刷怪塔一段时间后，发现插件记录到大量的烈焰人被三叉戟攻击和烈焰人死亡的事件（烈焰人正常生成并正常被击杀，但没有掉落物）。
卸载除BehaviorLog外的所有插件重新测试结果不变，可能是假人在地狱加载的三叉戟击杀生物没有掉落物。

**Comment by Jasonzyt** [comment]
会不会是三叉戟的所有者不在旁边？

**Comment by win-researcher** [comment]
> 会不会是三叉戟的所有者不在旁边？

我试一下让假人扔三叉戟

**Comment by win-researcher** [comment]
已解决
