### ISSUE TITLE
希望WebSocket服务器允许外网连接

### ISSUE THREAD

**Issue by XCLHove** [ddf8196/FakePlayer#53]
希望WebSocket服务器允许外网连接

**Comment by Jasonzyt** [comment]
WebSocket内容都是明文传输，外网连接会有风险，以后可能会考虑加入AES加密

**Comment by XCLHove** [comment]
这个问题用户不是可以通过是否开放端口解决嘛

**Comment by ddf8196** [comment]
目前是明文传输且无验证，开放了端口任何人都能连接并控制假人，存在安全风险

**Comment by Jasonzyt** [comment]
如果实在有需要，可以自己搓个轮子在本地转发websocket消息

**Comment by WuTongLiRan** [comment]
我搞了个反向代理，成功让外网连接上程序
