### ISSUE TITLE
无法启动程序

### ISSUE THREAD

**Issue by zjw666nwn** [ddf8196/FakePlayer#54]
**Version & Environment 软件版本和环境**
 - BDS Version [e.g. 1.18.12]
 - FakePlayer Version [e.g. 0.5.3]

**Describe the bug 你的问题的描述**
无法启动程序

**To Reproduce(Optional) 复现该问题的方法(可选)**
Steps to reproduce the behavior

**Screenshots or log 截图或日志**
If applicable, add screenshots or log to help explain your problem.

**Additional content 附加内容**
Add any other content about the problem here.

**Comment by Jasonzyt** [comment]
错误日志

**Comment by zjw666nwn** [comment]
> 请提供错误日志，确保您安装了 jre8


Uploading Screenrecorder-2022-03-20-22-33-23-277.mp4…

**Comment by Jasonzyt** [comment]
视频似乎没传上来

**Comment by zjw666nwn** [comment]
> 视频似乎没传上来


Uploading Screenrecorder-2022-03-20-22-33-23-277.mp4…

**Comment by Jasonzyt** [comment]
还是没传上来哇

**Comment by zjw666nwn** [comment]
> 视频似乎没传上来


https://user-images.githubusercontent.com/64683635/159167647-7c5cc732-803a-42b0-ae2e-d234980fcba3.mp4

**Comment by zjw666nwn** [comment]
等等

> 还是没传上来哇

**Comment by Jasonzyt** [comment]
看到了，用命令行打开bat脚本，输出截个图

**Comment by zjw666nwn** [comment]
> 看到了，用打开一个蝙蝠脚本，输出截图图

没有

**Comment by ddf8196** [comment]
试试在cmd中输入java -version查看是否能正确输出java版本信息

**Comment by zjw666nwn** [comment]
![Screenshot_2022-03-20-22-40-04-456_com microsoft rdc android](https://user-image


> 尝试在cmd中输入java -version查看是否能正确输出java版本信息

能

**Comment by zjw666nwn** [comment]
> 尝试在cmd中输入java -version查看是否能正确输出java版本信息

![Screenshot_2022-03-20-22-43-05-939_com microsoft rdc android](https://user-images.githubusercontent.com/64683635/159167960-bdb07fa6-a382-47f6-b06f-40d1e0a39533.jpg)

**Comment by Jasonzyt** [comment]
要java 8的

**Comment by zjw666nwn** [comment]
> 要java 8的

这不是Java8吗
![Screenshot_2022-03-20-22-44-32-712_com microsoft rdc android](https://user-images.githubusercontent.com/64683635/159168025-d9ea68fb-eae3-4b42-9a60-c4b8c89b33ec.jpg)

**Comment by ddf8196** [comment]
再试试用cmd运行FakePlayer-GUI.bat查看输出

**Comment by zjw666nwn** [comment]
> 再试试用cmd运行FakePlayer-GUI.bat查看输出

没有输出

**Comment by zjw666nwn** [comment]
> 再试试用cmd运行FakePlayer-GUI.bat查看输出

FakePlayer.bat有

**Comment by zjw666nwn** [comment]
> > 再试试用cmd运行FakePlayer-GUI.bat查看输出
> 
> 没有输出

等等gui出来了

**Comment by zjw666nwn** [comment]
GUI

**Comment by Jasonzyt** [comment]
草 那没毛病啊

**Comment by zjw666nwn** [comment]
> GUI

现在应该都正常了

**Comment by zjw666nwn** [comment]
> 草 那没毛病啊

但是第一次直接开就是打不开
