### ISSUE TITLE
1.18.31服务端按要求配置完整，无法连接

### ISSUE THREAD

**Issue by mrmagic2020** [ddf8196/FakePlayer#56]
**Version & Environment 软件版本和环境**
 - BDS Version [e.g. 1.16.40]
 - FakePlayer Version [e.g. 5.2.0]

**Describe the bug 你的问题的描述**

**To Reproduce(Optional) 复现该问题的方法(可选)**
Steps to reproduce the behavior

**Screenshots or log 截图或日志**
If applicable, add screenshots or log to help explain your problem.

**Additional content 附加内容**
Add any other content about the problem here.
显示内容：
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException

**Comment by mrmagic2020** [comment]
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException
假人试图连接的时候，链接失败，这个是gui显示的内容🙏

**Comment by Jasonzyt** [comment]
确定你服务器端口之类的填写正确？trust-keys加进server.properties并重启没有？

**Comment by mrmagic2020** [comment]
全部按照要求配置的，尝试连接的时候显示这个：
[2022.05.01 16:53:46] test 协议版本获取失败,尝试使用默认协议版本(408)连接
[2022.05.01 16:53:46] test 已停止
[2022.05.01 16:53:46] test 已断开连接: java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException

**Comment by mrmagic2020** [comment]
请问怎么解决呢
