### ISSUE TITLE
假人客户端在服务器上无法打开

### ISSUE THREAD

**Issue by ghost** [ddf8196/FakePlayer#58]
**Version & Environment 软件版本和环境**
 - BDS Version [e.g. 1.18.33.02]
 - FakePlayer Version [e.g. 5.4.0]

**Describe the bug 你的问题的描述**
只显示一下cmd窗口，gui并没有打开

**To Reproduce(Optional) 复现该问题的方法(可选)**
Steps to reproduce the behavior

**Screenshots or log 截图或日志**
If applicable, add screenshots or log to help explain your problem.

**Additional content 附加内容**
Add any other content about the problem here.

**Comment by f0l9y8f7i6r5e4** [comment]
0.5.3可以正常打开，但0.5.4不行

**Comment by f0l9y8f7i6r5e4** [comment]
求回复！

**Comment by Ysuha** [comment]
这个问题我也遇到了，后来发现估计是服务器配置不够的问题导致要加载比较久，你稍微等一会就出来了
