### ISSUE TITLE
麻烦更新一下，1.19 谢谢

### ISSUE THREAD

**Issue by daqueque** [ddf8196/FakePlayer#59]
麻烦更新一下，1.19 谢谢

**Comment by Jasonzyt** [comment]
[tags/v0.5.5](https://github.com/ddf8196/FakePlayer/releases/tag/v0.5.5)

**Comment by daqueque** [comment]
> [tags/v0.5.5](https://github.com/ddf8196/FakePlayer/releases/tag/v0.5.5)

谢谢
