### ISSUE TITLE
将协议升级到428吧

### ISSUE THREAD

**Issue by yqs112358** [ddf8196/FakePlayer#6]
1.16.210将协议升级到了428
据说没啥内容修改
建议直接放开协议版本范围限制😂方便我们直接改配置文件

**Comment by ddf8196** [comment]
并没有对协议版本进行限制。
目前不支持协议版本428是因为没有更新协议库，目前使用的版本的协议库最高支持的协议版本为422
现在协议版本是自动获取的，一般无需手动设置，配置文件中的defaultProtocolVersion是自动获取失败时默认使用的协议版本

**Comment by ddf8196** [comment]
稍后我会发布一个更新了协议库，支持1.16.210的版本

**Comment by ddf8196** [comment]
新版本已发布，支持1.16.210

**Comment by ddf8196** [comment]
请问"放开协议版本范围限制"具体指的是什么，假人从0.2.0版本开始就已经没有再对协议版本进行限制

**Comment by yqs112358** [comment]
> 请问"放开协议版本范围限制"具体指的是什么，假人从0.2.0版本开始就已经没有再对协议版本进行限制

emm没事了
我之前以为更改协议只要单纯修改数字罢了
原来还要编译新版本的协议库

**Comment by yqs112358** [comment]
真的很好用！支持一下
有兴趣到www.minebbs.com宣传一下吗
现在BDS相关开发者大部分都在这里
