### ISSUE TITLE
开启后服务器崩溃

### ISSUE THREAD

**Issue by Ysuha** [ddf8196/FakePlayer#66]
**Version & Environment 软件版本和环境**
 - BDS Version [e.g. 1.19.10]
 - FakePlayer Version [e.g. 0.5.6]

**Describe the bug 你的问题的描述**
因为没有设置验证，所以直接在服务器运行的时候开启，结果后台报错，服务器直接崩溃

**Screenshots or log 截图或日志**
服务器后台信息：
[Crashed!] -- Unhandled Exception in -> AntiToolbox.dll -- Exception Code: 0xC0000005 -- Minidump generated in Directory ./logs/Crash [StackTrace] Function THookTemplate<325791933921903840,8127861872949011038>::_hook at 0x7FF8971C5B30 [AntiToolbox.dll] -- At File D:\a\LiteLoaderPlugins\LiteLoaderPlugins\AntiToolbox\AntiToolbox.cpp : Line 134 [StackTrace] Function EndTag::set at 0x7FF8855C5D80 [LiteLoader.dll<2.4.0.2290>] 
[StackTrace] Function VanillaServerNetworkHandler::handle at 0x7FF730C69540 
[bedrock_server_mod.exe<1.19.10.03>] 
[StackTrace] Function <lambda_37d2627b9703ec3c85a127e9134c5ccf>::operator() at 0x7FF730FA7A40 [bedrock_server_mod.exe<1.19.10.03>] [StackTrace] Function NetworkHandler::runEvents at 0x7FF730FABEA0 [bedrock_server_mod.exe<1.19.10.03>] [StackTrace] Function Minecraft::update at 0x7FF7314760F0 [bedrock_server_mod.exe<1.19.10.03>] [StackTrace] Function ServerInstance::_update at 0x7FF73148CBE0 [bedrock_server_mod.exe<1.19.10.03>] [StackTrace] Function <lambda_a0aefe274f5913ecbd2fdf009aa305ae>::operator() at 0x7FF73148B210 [bedrock_server_mod.exe<1.19.10.03>] [StackTrace] Function std::thread::_Invoke<std::tuple<<lambda_a0aefe274f5913ecbd2fdf009aa305ae> >,0> at 0x7FF7314885E0 [bedrock_server_mod.exe<1.19.10.03>] [StackTrace] Function o_exp at 0x7FF8A6812630 [ucrtbase.dll<6.2.17763.1490>] [StackTrace] Function BaseThreadInitThunk at 0x7FF8A7CA7960 [KERNEL32.DLL<6.2.17763.2628>] [StackTrace] Function RtlUserThreadStart at 0x7FF8AA0CA2D0 [ntdll.dll<6.2.17763.2628>] [StackTrace] Function NetworkHandler::_sortAndPacketizeEvents at 0x7FF730FA8EB0 [bedrock_server_mod.exe<1.19.10.03>]

**Comment by Jasonzyt** [comment]
去AntiToolBox仓库问
