### ISSUE TITLE
SelectSlot有时操作无效

### ISSUE THREAD

**Issue by yqs112358** [ddf8196/FakePlayer#79]
**Version & Environment 软件版本和环境**
 - BDS Version 1.19.41
 - FakePlayer Version 0.5.10

**Describe the bug 你的问题的描述**
见截图
<img width="409" alt="image" src="https://user-images.githubusercontent.com/37969157/204565942-7d26da60-19a2-4bd2-b69e-bae168935c0b.png">
selectSlot 9 或 selectSlot 10时（刚扔进去的三叉戟）时，选择失败
但是选一个比较小的数（selectSlot 2）却会成功

后面扔给假人一个铁块，选择铁块（selectSlot 11），又执行失败
<img width="407" alt="image" src="https://user-images.githubusercontent.com/37969157/204566593-c09109cc-4f6c-4639-9a4b-5a359b7a20fd.png">
整个过程后台无报错信息输出

**To Reproduce(Optional) 复现该问题的方法(可选)**
玄学问题，不知道如何复现

**Comment by SkyAerope** [comment]
selectSlot只能0-8，wiki里面写有了
